'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''
final_value = 0
sequence = [1,2]
final_sum = 0

while final_value <= 4000000:
    current_length = len(sequence)
    final_value = sequence[current_length-1]+sequence[current_length-2]
    if final_value<=4000000:
        sequence.append(final_value)
    else:
        pass

for i in sequence:
    if i % 2 == 0:
        final_sum+=i
    else:
        pass

print(final_sum)
